# Generated by Django 6.0.3 on 2026-04-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0002_alter_livro_options_alter_lotecadastro_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tombo', models.CharField(max_length=50, unique=True, verbose_name='Codigo de patrimonio/tombo')),
                ('codigo_barras_interno', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo de barras interno')),
                ('localizacao_fisica', models.CharField(max_length=150, verbose_name='Localizacao fisica')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponivel'), ('EMPRESTADO', 'Emprestado'), ('RESERVADO', 'Reservado'), ('MANUTENCAO', 'Manutencao')], db_index=True, default='DISPONIVEL', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de aquisicao')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='catalogo.livro', verbose_name='Livro')),
                ('lote_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exemplares', to='core.lotecadastro', verbose_name='Lote de cadastro')),
            ],
            options={
                'verbose_name': 'Exemplar',
                'verbose_name_plural': 'Exemplares',
                'ordering': ['codigo_tombo'],
                'indexes': [models.Index(fields=['codigo_tombo'], name='acervo_exem_codigo__2a59c0_idx'), models.Index(fields=['status'], name='acervo_exem_status_b0eb51_idx'), models.Index(fields=['localizacao_fisica'], name='acervo_exem_localiz_6a2b9a_idx')],
            },
        ),
    ]
