# Generated by Django 6.0.3 on 2026-04-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplar',
            name='codigo_barras_interno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras interno'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='codigo_tombo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de patrimônio/tombo'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='data_aquisicao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de aquisição'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='localizacao_fisica',
            field=models.CharField(max_length=150, verbose_name='Localização física'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='exemplar',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADO', 'Emprestado'), ('RESERVADO', 'Reservado'), ('MANUTENCAO', 'Manutenção')], db_index=True, default='DISPONIVEL', max_length=20, verbose_name='Situação'),
        ),
    ]
