# Generated by Django 6.0.3 on 2026-04-13 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulacao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_emprestimo'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='acao',
            field=models.CharField(max_length=80, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True, verbose_name='Data do empréstimo'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_prevista_devolucao',
            field=models.DateField(verbose_name='Data prevista de devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Atrasado')], db_index=True, default='ATIVO', max_length=12, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='emprestimo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multa', to='circulacao.emprestimo', verbose_name='Empréstimo'),
        ),
        migrations.AlterField(
            model_name='multa',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10, verbose_name='Situação do pagamento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de expiração'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('ATIVA', 'Ativa'), ('ATENDIDA', 'Atendida'), ('CANCELADA', 'Cancelada'), ('EXPIRADA', 'Expirada')], db_index=True, default='ATIVA', max_length=12, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
