# Generated by Django 6.0.3 on 2026-03-25 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(max_length=100, verbose_name='Número da Nota Fiscal')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade de Livros')),
                ('data_hora_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_cadastrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Livro')),
                ('autor', models.CharField(max_length=150, verbose_name='Autor')),
                ('codigo_barras', models.CharField(max_length=50, unique=True, verbose_name='Código de Barras')),
                ('categoria', models.CharField(choices=[('FIC', 'Ficção'), ('MIST', 'Mistério'), ('ROM', 'Romance'), ('TEC', 'Tecnologia'), ('OUT', 'Outros')], max_length=4, verbose_name='Categoria')),
                ('classificacao', models.IntegerField(choices=[(1, '1 Estrela (Péssimo)'), (2, '2 Estrelas (Ruim)'), (3, '3 Estrelas (Regular)'), (4, '4 Estrelas (Bom)'), (5, '5 Estrelas (Excelente)')], verbose_name='Classificação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_cadastrados', to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='core.lotecadastro')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('precisa_trocar_senha', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
