# Generated by Django 6.0.3 on 2026-04-13 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['-data_cadastro'], 'verbose_name': 'Livro (legado por lote)', 'verbose_name_plural': 'Livros (legado por lote)'},
        ),
        migrations.AlterModelOptions(
            name='lotecadastro',
            options={'ordering': ['-data_hora_cadastro'], 'verbose_name': 'Lote de cadastro', 'verbose_name_plural': 'Lotes de cadastro'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de usuario', 'verbose_name_plural': 'Perfis de usuarios'},
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('FIC', 'Ficcao'), ('MIST', 'Misterio'), ('ROM', 'Romance'), ('TEC', 'Tecnologia'), ('OUT', 'Outros')], max_length=4, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='classificacao',
            field=models.IntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], verbose_name='Classificacao'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='codigo_barras',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codigo de barras'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livros_legado', to='core.lotecadastro', verbose_name='Lote'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='lotecadastro',
            name='data_hora_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/hora do cadastro'),
        ),
        migrations.AlterField(
            model_name='lotecadastro',
            name='nota_fiscal',
            field=models.CharField(max_length=100, verbose_name='Numero da nota fiscal'),
        ),
        migrations.AlterField(
            model_name='lotecadastro',
            name='quantidade',
            field=models.PositiveIntegerField(verbose_name='Quantidade de livros'),
        ),
        migrations.AlterField(
            model_name='lotecadastro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='precisa_trocar_senha',
            field=models.BooleanField(default=True, verbose_name='Precisa trocar senha'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
