# Generated by Django 6.0.3 on 2026-04-13 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_livro_options_alter_lotecadastro_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de usuário', 'verbose_name_plural': 'Perfis de usuários'},
        ),
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('FIC', 'Ficção'), ('MIST', 'Mistério'), ('ROM', 'Romance'), ('TEC', 'Tecnologia'), ('OUT', 'Outros')], max_length=4, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='classificacao',
            field=models.IntegerField(choices=[(1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='codigo_barras',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de barras'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='lotecadastro',
            name='data_hora_cadastro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e hora do cadastro'),
        ),
        migrations.AlterField(
            model_name='lotecadastro',
            name='nota_fiscal',
            field=models.CharField(max_length=100, verbose_name='Número da nota fiscal'),
        ),
        migrations.AlterField(
            model_name='lotecadastro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='matricula',
            field=models.CharField(max_length=20, unique=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
