# Generated by Django 6.0.3 on 2026-04-13 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, unique=True, verbose_name='Nome')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, verbose_name='Nacionalidade')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, unique=True, verbose_name='Nome')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Editora',
                'verbose_name_plural': 'Editoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220, verbose_name='Titulo')),
                ('subtitulo', models.CharField(blank=True, max_length=220, verbose_name='Subtitulo')),
                ('isbn', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Informe um ISBN valido (10 a 17 caracteres, com numeros, X e hifen).', regex='^[0-9Xx\\-]{10,17}$')], verbose_name='ISBN')),
                ('ano_publicacao', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1450), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de publicacao')),
                ('edicao', models.CharField(blank=True, max_length=50, verbose_name='Edicao')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('autores', models.ManyToManyField(related_name='livros', to='catalogo.autor', verbose_name='Autores')),
                ('categorias', models.ManyToManyField(blank=True, related_name='livros', to='catalogo.categoria', verbose_name='Categorias')),
                ('editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='catalogo.editora', verbose_name='Editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['titulo'], name='catalogo_li_titulo_f00f2c_idx'), models.Index(fields=['isbn'], name='catalogo_li_isbn_5a2392_idx'), models.Index(fields=['ano_publicacao'], name='catalogo_li_ano_pub_9e31d3_idx')],
            },
        ),
    ]
