# Generated by Django 6.0.3 on 2026-04-13 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_publicacao',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1450), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano de publicação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.CharField(blank=True, max_length=50, verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='Informe um ISBN válido (10 a 17 caracteres, com números, X e hífen).', regex='^[0-9Xx\\-]{10,17}$')], verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=220, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=220, verbose_name='Título'),
        ),
    ]
